"""Training readiness thresholds for the community edition.

These are default heuristic thresholds for training-management reference only.
They are not medical standards, injury probabilities, or fixed safety zones.
"""

ALGORITHM_VERSION = "readiness-rules-v1"
THRESHOLD_VERSION = "readiness-thresholds-v1"

MIN_HISTORY_DAYS_HIGH_QUALITY = 28
MIN_HISTORY_DAYS_MEDIUM_QUALITY = 14
LOW_SRPE_COVERAGE_RATIO = 0.50
MEDIUM_SRPE_COVERAGE_RATIO = 0.70
HIGH_SRPE_COVERAGE_RATIO = 0.80
MEDIUM_RECOVERY_COVERAGE_RATIO = 3 / 7
HIGH_RECOVERY_COVERAGE_RATIO = 5 / 7

LOAD_CHANGE_WEAK_PERCENT = 15.0
LOAD_CHANGE_MODERATE_PERCENT = 30.0
SRPE_CHANGE_WEAK_PERCENT = 15.0
SRPE_CHANGE_MODERATE_PERCENT = 30.0
SESSION_LONGEST_RATIO_MODERATE = 1.25
KEY_WORKOUT_RPE_HIGH = 8
KEY_WORKOUT_RPE_VERY_HIGH = 9
HIGH_RPE_STREAK_COUNT = 2
RECOVERY_LOW_VALUE = 2
RECOVERY_HIGH_FATIGUE_VALUE = 4
RECOVERY_STREAK_DAYS = 2
PAIN_MODERATE_LEVEL = 4
PAIN_STRONG_LEVEL = 7

ROLLING_7D_DAYS = 7
BASELINE_28D_DAYS = 28
SESSION_LONGEST_LOOKBACK_DAYS = 30
