const STATUS_LABELS: Record<string, string> = {
  active: "正常",
  inactive: "已停用",
  connected: "已连接",
  disconnected: "未连接",
  reauthentication_required: "需要重新认证",
  temporarily_unavailable: "暂时不可用",
  draft: "草稿",
  accepted: "已应用",
  rejected: "已拒绝",
  pending: "等待中",
  queued: "排队中",
  running: "同步中",
  succeeded: "成功",
  success: "成功",
  failed: "失败",
  partially_succeeded: "部分成功",
  partial_success: "部分成功",
  ready: "可应用",
  conflict: "有冲突",
  validation_failed: "校验失败",
  applied: "已应用",
  cancelled: "已取消",
  matched: "已匹配",
  unplanned: "计划外",
  needs_review: "待处理",
  ignored: "已忽略",
  synced: "已同步",
  not_applied: "未写入",
  log_created: "已写入训练日志",
  log_merged: "已合并已有记录",
  linked_existing: "已关联已有日志",
  completed_high: "高质量完成",
  completed_normal: "正常完成",
  completed_adjusted: "调整后完成",
  missed: "缺课",
  skipped: "跳过",
  rest: "休息",
  rest_or_cancelled: "休息 / 取消",
  not_started: "未开始",
  unknown: "未知",
  available: "可用",
  disabled_in_production: "未开放",
  incremental: "最新",
  initial_backfill: "首次回填",
  recent_7d: "最近 7 天",
  recent_30d: "最近 30 天",
  custom_range: "自定义范围",
};

export function statusLabel(value?: string | null) {
  if (!value) return "-";
  return STATUS_LABELS[value] || value;
}
