from __future__ import annotations

from enum import Enum


class KnowledgeCategory(str, Enum):
    TRAINING_SYSTEM = "TRAINING_SYSTEM"
    PERIODIZATION = "PERIODIZATION"
    THRESHOLD = "THRESHOLD"
    INTERVAL = "INTERVAL"
    LONG_RUN = "LONG_RUN"
    RECOVERY = "RECOVERY"
    STRENGTH = "STRENGTH"
    INJURY_PREVENTION = "INJURY_PREVENTION"
    LOAD_MANAGEMENT = "LOAD_MANAGEMENT"
    TAPER = "TAPER"
    GENERAL = "GENERAL"


class KnowledgeSourceType(str, Enum):
    BOOK_SUMMARY = "BOOK_SUMMARY"
    PAPER_SUMMARY = "PAPER_SUMMARY"
    GUIDELINE_SUMMARY = "GUIDELINE_SUMMARY"
    COACHING_NOTE = "COACHING_NOTE"
    INTERNAL_RULE_EXPLANATION = "INTERNAL_RULE_EXPLANATION"
    ORIGINAL_CONTENT = "ORIGINAL_CONTENT"


class KnowledgeEvidenceLevel(str, Enum):
    PRIMARY = "PRIMARY"
    SECONDARY = "SECONDARY"
    EXPERT_CONSENSUS = "EXPERT_CONSENSUS"
    INTERNAL = "INTERNAL"
    UNKNOWN = "UNKNOWN"


class KnowledgeDocumentStatus(str, Enum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    DEPRECATED = "DEPRECATED"
    ARCHIVED = "ARCHIVED"


class LicenseStatus(str, Enum):
    ORIGINAL = "ORIGINAL"
    SUMMARY_ONLY = "SUMMARY_ONLY"
    OPEN_LICENSE = "OPEN_LICENSE"
    PERMISSION_GRANTED = "PERMISSION_GRANTED"
    REFERENCE_ONLY = "REFERENCE_ONLY"


class SourceUsagePolicy(str, Enum):
    ORIGINAL_CONTENT = "ORIGINAL_CONTENT"
    SELF_WRITTEN_SUMMARY = "SELF_WRITTEN_SUMMARY"
    LICENSED_EXCERPT = "LICENSED_EXCERPT"
    CITATION_ONLY = "CITATION_ONLY"
