from enum import Enum


class DeviationType(str, Enum):
    MISSED_SESSION = "MISSED_SESSION"
    EXTRA_SESSION = "EXTRA_SESSION"
    DISTANCE_UNDER = "DISTANCE_UNDER"
    DISTANCE_OVER = "DISTANCE_OVER"
    DURATION_UNDER = "DURATION_UNDER"
    DURATION_OVER = "DURATION_OVER"
    KEY_SESSION_MISSED = "KEY_SESSION_MISSED"
    LONG_RUN_MISSED = "LONG_RUN_MISSED"
    INTENSITY_HIGHER_THAN_PLANNED = "INTENSITY_HIGHER_THAN_PLANNED"
    INTENSITY_LOWER_THAN_PLANNED = "INTENSITY_LOWER_THAN_PLANNED"
    UNMATCHED_LOG = "UNMATCHED_LOG"
    DUPLICATE_OR_AMBIGUOUS_LOG = "DUPLICATE_OR_AMBIGUOUS_LOG"


class DeviationSeverity(str, Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    ATTENTION = "ATTENTION"


class WeeklyDataQualityLevel(str, Enum):
    COMPLETE = "COMPLETE"
    PARTIAL = "PARTIAL"
    INSUFFICIENT = "INSUFFICIENT"
    CONFLICTED = "CONFLICTED"


class WeeklyClassificationStatus(str, Enum):
    ON_TRACK = "ON_TRACK"
    UNDER_COMPLETED = "UNDER_COMPLETED"
    OVER_COMPLETED = "OVER_COMPLETED"
    INTENSITY_IMBALANCE = "INTENSITY_IMBALANCE"
    RECOVERY_CONCERN = "RECOVERY_CONCERN"
    MIXED = "MIXED"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
