import type { RunnerStateSnapshot } from "@/types/runnerState";

export function createRunnerStateSnapshot(): RunnerStateSnapshot {
  return {
    identity: {
      runner_id: 900001,
      generated_at: "2026-07-16T10:00:00+08:00",
      timezone: "Asia/Shanghai",
      calculation_window_end: "2026-07-15",
      calculation_window_start_7d: "2026-07-09",
      calculation_window_start_28d: "2026-06-18",
    },
    goal_context: { race_distance: null, race_date: null, target_time_seconds: null, weeks_remaining: null },
    recent_training: {
      distance_7d_km: 52,
      distance_28d_km: 160,
      duration_7d_minutes: 280,
      duration_28d_minutes: 920,
      sessions_7d: 5,
      sessions_28d: 18,
      completed_sessions_7d: 5,
      completed_sessions_28d: 17,
      planned_sessions_7d: 5,
      planned_sessions_28d: 18,
      completion_rate_7d: 1,
      completion_rate_28d: 0.9444,
      average_rpe_7d: 5.5,
      average_rpe_28d: 5.2,
    },
    intensity: {
      easy_distance_7d_km: 30,
      moderate_distance_7d_km: 14,
      hard_distance_7d_km: 8,
      easy_distance_28d_km: 95,
      moderate_distance_28d_km: 42,
      hard_distance_28d_km: 23,
      hard_distance_ratio_7d: 0.1538,
      hard_distance_ratio_28d: 0.1438,
      quality_sessions_7d: 2,
      quality_sessions_28d: 7,
      long_run_distance_7d_km: 18,
      long_run_distance_28d_km: 55,
      days_since_last_quality_session: 2,
    },
    inferred_state: {
      fitness_state: "UNKNOWN",
      fatigue_state: "NORMAL",
      load_trend: "UNKNOWN",
      training_consistency: "HIGH",
      training_phase: "UNKNOWN",
      weaknesses: [],
      risk_flags: [],
    },
    data_quality: {
      data_quality_level: "HIGH",
      confidence: 0.86,
      available_fields: ["training_logs", "actual_distance_km", "actual_duration_seconds", "rpe", "heart_rate", "planned_workouts"],
      missing_fields: [],
      valid_workout_count_7d: 5,
      valid_workout_count_28d: 17,
      rpe_coverage_7d: 0.8,
      rpe_coverage_28d: 0.72,
      heart_rate_coverage_7d: 0.6,
      heart_rate_coverage_28d: 0.5,
      limitations: ["intensity_distance_uses_main_workout_type"],
    },
    derived_metrics: {
      distance_previous_21d_km: 108,
      sessions_previous_21d: 13,
      valid_workout_count_previous_21d: 12,
      average_rpe_previous_21d: 5.1,
      rpe_coverage_previous_21d: 0.7,
      planned_sessions_previous_21d: 13,
      completed_planned_sessions_previous_21d: 12,
      completion_rate_previous_21d: 0.9231,
      active_weeks_previous_21d: 3,
      active_weeks_28d: 4,
      weekly_session_mean_28d: 4.25,
      weekly_session_cv_28d: 0.1,
      high_intensity_sessions_7d: 1,
      high_intensity_sessions_28d: 5,
      maximum_consecutive_high_intensity_days_7d: 1,
    },
    volume_trend: {
      state: "STABLE",
      previous_21d_weekly_average_km: 36,
      volume_ratio: 1.2,
      reason_codes: ["RECENT_VOLUME_STABLE"],
      evidence: [
        { metric: "distance_7d_km", value: 52, threshold: null, unit: "km", window: "recent_7d", source: "runner_state_foundation", used: true },
      ],
      ruleset_version: "runner-state-rules-1.0.0",
    },
    training_consistency: {
      state: "HIGH",
      basis: "PLAN_COMPLETION",
      reason_codes: ["HIGH_PLAN_COMPLETION"],
      evidence: [],
      evidence_coverage: 1,
      ruleset_version: "runner-state-rules-1.0.0",
    },
    fatigue: {
      state: "NORMAL",
      score: 0,
      triggered_signals: [],
      skipped_signals: ["RPE_CHANGE"],
      reason_codes: ["INSUFFICIENT_RPE_COVERAGE"],
      evidence: [],
      available_signal_count: 4,
      total_signal_count: 5,
      evidence_coverage: 0.8,
      ruleset_version: "runner-state-rules-1.0.0",
    },
    risk_flags: [],
    inference_metadata: {
      ruleset_version: "runner-state-rules-1.0.0",
      calculated_at: "2026-07-16T10:00:00+08:00",
      reason_codes: ["TRAINING_PHASE_UNAVAILABLE"],
      limitations: ["training_phase_unavailable_no_structured_cycle_phase"],
    },
  };
}
