from __future__ import annotations

from enum import Enum


class AgentIntent(str, Enum):
    TODAY_RECOMMENDATION = "TODAY_RECOMMENDATION"
    WEEKLY_REVIEW = "WEEKLY_REVIEW"
    EXPLAIN_RUNNER_STATE = "EXPLAIN_RUNNER_STATE"
    GENERAL_TRAINING_QUESTION = "GENERAL_TRAINING_QUESTION"
    UNKNOWN = "UNKNOWN"


class AgentRunStatus(str, Enum):
    SUCCEEDED = "SUCCEEDED"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    TOOL_FAILED = "TOOL_FAILED"
    MODEL_FAILED = "MODEL_FAILED"
    REJECTED = "REJECTED"


class AgentToolStatus(str, Enum):
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    NOT_FOUND = "NOT_FOUND"
    NOT_ALLOWED = "NOT_ALLOWED"
    INVALID_ARGUMENTS = "INVALID_ARGUMENTS"


class AgentRiskLevel(str, Enum):
    LOW = "LOW"
    MODERATE = "MODERATE"
    HIGH = "HIGH"
    UNKNOWN = "UNKNOWN"


class AgentTraceEventType(str, Enum):
    REQUEST_VALIDATED = "REQUEST_VALIDATED"
    CONTEXT_BUILT = "CONTEXT_BUILT"
    MODEL_CALL = "MODEL_CALL"
    TOOL_CALL = "TOOL_CALL"
    RESPONSE_VALIDATED = "RESPONSE_VALIDATED"
    RUN_COMPLETED = "RUN_COMPLETED"
    ERROR = "ERROR"


class AgentTraceStatus(str, Enum):
    STARTED = "STARTED"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    REJECTED = "REJECTED"
